// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  bento: dynamic(() => import("./Bento")),
  call_to_action: dynamic(() => import("./CallToAction")),
  call_to_action_slice: dynamic(() => import("./CallToActionSlice")),
  case_study: dynamic(() => import("./CaseStudies")),
  cases: dynamic(() => import("./Cases")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  fk_landing_full: dynamic(() => import("./FkLandingFull")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  hero_unboxed: dynamic(() => import("./HeroUnboxed")),
  integrations: dynamic(() => import("./Integrations")),
  rich_text: dynamic(() => import("./RichText")),
  rich_text_slice: dynamic(() => import("./RichTextSlice")),
  showcase: dynamic(() => import("./Showcase")),
};
